project_id = "qsunfiextzzdxnsyrkkc"

[functions.address-autocomplete]
verify_jwt = false

[functions.address-details]
verify_jwt = false

[functions.hello-world]
verify_jwt = false

[functions.upload-file]
verify_jwt = false

[functions.create-customer]
verify_jwt = false

[functions.get-image]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.activate-account]
verify_jwt = false

[functions.generate-discount]
verify_jwt = false
