// Curated list of common disposable / temporary / throwaway email providers.
// Used as a lightweight spam filter on signup. Not exhaustive — focuses on
// the most-abused providers. Catches the bulk of low-effort spam without
// blocking real B2B users.
//
// Keep entries lowercase, no leading "@". Subdomains are matched as well.
export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "sharklasers.com",
  "grr.la",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "tempmail.com",
  "temp-mail.com",
  "temp-mail.org",
  "tempmailo.com",
  "tempmail.net",
  "tempmail.plus",
  "tempmailaddress.com",
  "throwawaymail.com",
  "throwawaymail.org",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "trashmail.com",
  "trashmail.net",
  "trashmail.de",
  "getnada.com",
  "nada.email",
  "dispostable.com",
  "fakeinbox.com",
  "fake-mail.net",
  "maildrop.cc",
  "mailnesia.com",
  "mintemail.com",
  "moakt.com",
  "spam4.me",
  "spambox.us",
  "spamgourmet.com",
  "mvrht.com",
  "mytemp.email",
  "mohmal.com",
  "emailondeck.com",
  "tutanota.com.tw",
  "fakemail.net",
  "inboxbear.com",
  "mailcatch.com",
  "harakirimail.com",
  "incognitomail.com",
  "jetable.org",
  "mailexpire.com",
  "discard.email",
  "discardmail.com",
  "anonymouse.org",
  "deadaddress.com",
  "emailtemporanea.net",
  "fastacura.com",
  "filzmail.com",
  "spambog.com",
  "spamherelots.com",
  "spamspot.com",
  "tempinbox.com",
  "tempemail.net",
  "tempemail.co",
  "tempr.email",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "byom.de",
  "discardmail.de",
  "einrot.com",
  "fudgerub.com",
  "letthemeatspam.com",
  "mailbidon.com",
  "mailblocks.com",
  "mailcat.biz",
  "mailfreeway.com",
  "mailimate.com",
  "mailme.lv",
  "mailmetrash.com",
  "mailshell.com",
  "mailtemp.info",
  "mailzilla.com",
  "mt2014.com",
  "no-spam.ws",
  "objectmail.com",
  "owlpic.com",
  "pookmail.com",
  "proxymail.eu",
  "punkass.com",
  "putthisinyourspamdatabase.com",
  "quickinbox.com",
  "rcpt.at",
  "recode.me",
  "recursor.net",
  "regbypass.com",
  "rmqkr.net",
  "safe-mail.net",
  "selfdestructingmail.com",
  "send-email.org",
  "shieldemail.com",
  "shitmail.me",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "snkmail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "spam.la",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spamcorptastic.com",
  "spamday.com",
  "spamfree24.com",
  "spamhole.com",
  "spaminator.de",
  "spamslicer.com",
  "spamthis.co.uk",
  "spamtroll.net",
  "speed.1s.fr",
  "supergreatmail.com",
  "supermailer.jp",
  "tagyourself.com",
  "talkinator.com",
  "teleworm.com",
  "teleworm.us",
  "tempalias.com",
  "tempemail.biz",
  "tempomail.fr",
  "temporarily.de",
  "temporarioemail.com.br",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "thankyou2010.com",
  "thecloudindex.com",
  "tilien.com",
  "tradermail.info",
  "trash2009.com",
  "trashdevil.com",
  "trashymail.com",
  "tyldd.com",
  "uggsrock.com",
  "veryrealemail.com",
  "wh4f.org",
  "whyspam.me",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "yopmail.gq",
  "yopmail.ml",
  "yuurok.com",
  "zehnminutenmail.de",
  "zoemail.org",
]);

/**
 * Returns true when the given email's domain (or its registrable parent
 * domain) appears in the disposable email list. Case-insensitive. Tolerant
 * of subdomains (e.g. `foo.mailinator.com` -> matches `mailinator.com`).
 */
export function isDisposableEmail(email: string | undefined | null): boolean {
  if (!email) return false;
  const at = email.lastIndexOf("@");
  if (at === -1) return false;
  const domain = email.slice(at + 1).trim().toLowerCase();
  if (!domain) return false;

  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) return true;

  // Walk up subdomains: a.b.example.com -> b.example.com -> example.com
  const parts = domain.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    const candidate = parts.slice(i).join(".");
    if (DISPOSABLE_EMAIL_DOMAINS.has(candidate)) return true;
  }
  return false;
}
