import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  // Emit asset URLs as relative paths ("./assets/...") so the build works
  // unchanged whether served at the site root, at /apps/apply (Shopify App
  // Proxy), or any other subpath. Required for the App Proxy mount because
  // Shopify rewrites the URL but the HTML response is returned verbatim.
  base: "./",
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [
    react(),
    mode === "development" && componentTagger(),
    // Inject fetchpriority="high" on the entry module script. Vite already
    // injects modulepreload for the entry's static imports during HTML
    // transformation, but this nudges the browser to prioritize the entry
    // fetch over images and lower-priority resources inside the iframe.
    {
      name: "boot-fetchpriority",
      transformIndexHtml(html: string) {
        return html.replace(
          /<script type="module" (crossorigin )?src="([^"]+)"><\/script>/,
          (_m: string, cors: string | undefined, src: string) =>
            `<script type="module" ${cors ?? ""}src="${src}" fetchpriority="high"></script>`
        );
      },
    },
    // Emit a /prefetch.js the parent Shopify theme can include on every
    // storefront page. It schedules <link rel="prefetch"> for the iframe's
    // hashed entry + vendor chunks during browser idle time, so when the
    // iframe opens the bundle is already in HTTP cache.
    //
    // CRITICAL — URL match invariant for cache hits (Chrome partitions cache
    // by top-level site + frame site + URL):
    //   The iframe is mounted at https://dropdeadextensions.com/apps/apply/...
    //   via Shopify App Proxy. Vite uses base: "./" so bundles resolve
    //   relative to the iframe document → the actual request URL the iframe
    //   makes is https://dropdeadextensions.com/apps/apply/assets/<hash>.js,
    //   NOT the apply.dropdeadextensions.com origin. We MUST emit the proxied
    //   storefront URL here so the prefetch hits the same cache entry the
    //   iframe will look up. Mismatched URLs would silently waste bandwidth.
    {
      name: "parent-prefetch-manifest",
      apply: "build" as const,
      generateBundle(_options: unknown, bundle: Record<string, any>) {
        // App Proxy mount point on the storefront — must match the live route.
        const proxyBase = "https://dropdeadextensions.com/apps/apply";
        const entryUrls = new Set<string>();
        for (const file of Object.values(bundle)) {
          if (file.type !== "chunk" || !file.isEntry) continue;
          entryUrls.add(file.fileName);
          for (const imp of (file.imports as string[]) || []) entryUrls.add(imp);
          // Entry CSS too — same partition, same win.
          for (const css of (file.viteMetadata?.importedCss as Set<string> | undefined) ?? []) {
            entryUrls.add(css);
          }
        }
        const urls = Array.from(entryUrls).map((u) => `${proxyBase}/${u}`);

        const script = `/* Auto-generated by vite. Prefetches the apply SPA bundle into the storefront's HTTP cache so the iframe boots from cache on first open. URLs match the App Proxy mount (dropdeadextensions.com/apps/apply/...) so the cache partition lines up. */
(function(){
  if (window.__APPLY_PREFETCHED__) return;
  window.__APPLY_PREFETCHED__ = true;
  // Skip prefetching for already-logged-in customers — they never see the iframe.
  // The theme exposes window.__customerLoggedIn (boolean) when known; absence is
  // treated as "guest" to avoid skipping prefetch on themes that haven't wired
  // the flag yet.
  if (window.__customerLoggedIn === true) return;
  var urls = ${JSON.stringify(urls)};
  function inject(){
    for (var i = 0; i < urls.length; i++) {
      var url = urls[i];
      var l = document.createElement('link');
      l.rel = 'prefetch';
      l.as = url.endsWith('.css') ? 'style' : 'script';
      l.href = url;
      l.crossOrigin = 'anonymous';
      document.head.appendChild(l);
    }
  }
  if ('requestIdleCallback' in window) {
    requestIdleCallback(inject, { timeout: 3000 });
  } else {
    setTimeout(inject, 1500);
  }
})();
`;
        (this as any).emitFile({
          type: "asset",
          fileName: "prefetch.js",
          source: script,
        });

        // Also emit Netlify-compatible _headers with Link: preload directives
        // for the SAME hashed filenames. This covers the case where the user
        // lands on the iframe directly (no parent prefetch ran) — the browser
        // starts fetching bundles as soon as the iframe response headers
        // arrive, in parallel with HTML body download. Self-versioning
        // because filenames are baked in at build time.
        const linkHeaders = Array.from(entryUrls)
          .map((u) => {
            const asAttr = u.endsWith(".css") ? "style" : "script";
            // Relative URL — works regardless of which origin (apply.* or App
            // Proxy) serves the document.
            return `  Link: </${u}>; rel=preload; as=${asAttr}; crossorigin`;
          })
          .join("\n");

        const headers = `# Auto-generated by vite. Do not edit by hand.
# Hashed asset chunks — long-lived immutable cache.
/assets/*
  Cache-Control: public, max-age=31536000, immutable
  Access-Control-Allow-Origin: *

# prefetch.js — short cache so the parent theme picks up new bundle URLs
# within minutes of a deploy. CORS open so cross-origin parents can load it.
/prefetch.js
  Cache-Control: public, max-age=300, must-revalidate
  Access-Control-Allow-Origin: *

# All HTML responses — never cache, always revalidate. Link: preload headers
# tell the browser to fetch the entry chunk + CSS as soon as the response
# starts arriving (before the HTML body finishes downloading).
/*
  Cache-Control: no-cache
${linkHeaders}
`;
        (this as any).emitFile({
          type: "asset",
          fileName: "_headers",
          source: headers,
        });
      },
    },
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // Split stable vendor code into long-lived chunks so a deploy that
        // only touches app code doesn't bust the React/Radix cache.
        manualChunks: {
          "react-vendor": ["react", "react-dom", "react-router"],
        },
      },
    },
  },
  test: {
    globals: true,
  },
}));
