import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { componentTagger } from "lovable-tagger";

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => ({
  // Emit asset URLs as relative paths ("./assets/...") so the build works
  // unchanged whether served at the site root, at /apps/apply (Shopify App
  // Proxy), or any other subpath. Required for the App Proxy mount because
  // Shopify rewrites the URL but the HTML response is returned verbatim.
  base: "./",
  server: {
    host: "::",
    port: 8080,
  },
  plugins: [
    react(),
    mode === "development" && componentTagger(),
    // Inject fetchpriority="high" on the entry module script. Vite already
    // injects modulepreload for the entry's static imports during HTML
    // transformation, but this nudges the browser to prioritize the entry
    // fetch over images and lower-priority resources inside the iframe.
    {
      name: "boot-fetchpriority",
      transformIndexHtml(html: string) {
        return html.replace(
          /<script type="module" (crossorigin )?src="([^"]+)"><\/script>/,
          (_m: string, cors: string | undefined, src: string) =>
            `<script type="module" ${cors ?? ""}src="${src}" fetchpriority="high"></script>`
        );
      },
    },
    // Emit a /prefetch.js the parent Shopify theme can include on every
    // storefront page. It schedules <link rel="prefetch"> for the iframe's
    // hashed entry + vendor chunks during browser idle time, so when the
    // iframe opens the bundle is already in HTTP cache. Versioned via the
    // hashed filenames; old prefetch.js consumers will request stale URLs
    // (which simply 404 — harmless) until the theme reloads the new version.
    {
      name: "parent-prefetch-manifest",
      apply: "build",
      generateBundle(_options, bundle) {
        const origin = "https://apply.dropdeadextensions.com";
        // Collect entry chunk + its static imports (vendor chunks, etc.).
        const entryUrls = new Set<string>();
        for (const file of Object.values(bundle)) {
          if (file.type !== "chunk" || !file.isEntry) continue;
          entryUrls.add(file.fileName);
          for (const imp of file.imports || []) entryUrls.add(imp);
        }
        const urls = Array.from(entryUrls).map((u) => `${origin}/${u}`);

        // Tiny script — runs on the parent Shopify storefront, not in the iframe.
        // Idempotent: a data-attribute guards against duplicate injection if the
        // theme accidentally loads prefetch.js twice.
        const script = `/* Auto-generated by vite. Prefetches the apply.dropdeadextensions.com SPA bundle into the parent storefront's HTTP cache so the iframe boots from cache on first open. */
(function(){
  if (window.__APPLY_PREFETCHED__) return;
  window.__APPLY_PREFETCHED__ = true;
  var urls = ${JSON.stringify(urls)};
  function inject(){
    for (var i = 0; i < urls.length; i++) {
      var l = document.createElement('link');
      l.rel = 'prefetch';
      l.as = 'script';
      l.href = urls[i];
      l.crossOrigin = 'anonymous';
      document.head.appendChild(l);
    }
  }
  if ('requestIdleCallback' in window) {
    requestIdleCallback(inject, { timeout: 3000 });
  } else {
    setTimeout(inject, 1500);
  }
})();
`;
        this.emitFile({
          type: "asset",
          fileName: "prefetch.js",
          source: script,
        });
      },
    },
  ].filter(Boolean),
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    rollupOptions: {
      output: {
        // Split stable vendor code into long-lived chunks so a deploy that
        // only touches app code doesn't bust the React/Radix cache.
        manualChunks: {
          "react-vendor": ["react", "react-dom", "react-router"],
        },
      },
    },
  },
  test: {
    globals: true,
  },
}));
