// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/get-my-registration.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-registration.ts
var get_my_registration_default = defineTool({
  name: "get_my_registration",
  title: "Get my registration",
  description: "Read the signed-in stylist's wholesale registration profile: account type, contact details, license number, salon details and application status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "id, account_type, first_name, last_name, email, phone_number, phone_country_code, business_name, city, state, zip_code, country, license_number, salon_size, salon_structure, school_name, school_state, business_operation_type, has_tax_exemption, social_media_handle, subscribe_order_updates, subscribe_promotions, subscribe_sms_promotions, application_status, created_at, updated_at"
    ).eq("id", ctx.getUserId() ?? "").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No registration profile found for this account yet." }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { registration: data }
    };
  }
});

// src/lib/mcp/tools/list-my-marketing-consent.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_my_marketing_consent_default = defineTool2({
  name: "list_my_marketing_consent",
  title: "List my marketing consent",
  description: "List the signed-in user's recorded marketing consent events (SMS and email opt-ins), newest first.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("marketing_consent_log").select("id, channel, granted, opt_in_level, email, phone_e164, created_at").order("created_at", { ascending: false }).limit(50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length ? JSON.stringify(rows, null, 2) : "No marketing consent records found for this account."
        }
      ],
      structuredContent: { count: rows.length, records: rows }
    };
  }
});

// src/lib/mcp/tools/update-my-communication-preferences.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";
var update_my_communication_preferences_default = defineTool3({
  name: "update_my_communication_preferences",
  title: "Update my communication preferences",
  description: "Update the signed-in user's marketing preferences and Instagram handle on their registration profile. Only the provided fields change.",
  inputSchema: {
    subscribe_order_updates: z.boolean().optional().describe("Receive transactional order update emails."),
    subscribe_promotions: z.boolean().optional().describe("Receive promotional emails."),
    subscribe_sms_promotions: z.boolean().optional().describe("Receive promotional text messages."),
    social_media_handle: z.string().trim().min(1).max(60).optional().describe("Instagram handle, with or without the leading @.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const patch = {};
    if (input.subscribe_order_updates !== void 0)
      patch.subscribe_order_updates = input.subscribe_order_updates;
    if (input.subscribe_promotions !== void 0)
      patch.subscribe_promotions = input.subscribe_promotions;
    if (input.subscribe_sms_promotions !== void 0)
      patch.subscribe_sms_promotions = input.subscribe_sms_promotions;
    if (input.social_media_handle !== void 0)
      patch.social_media_handle = input.social_media_handle.replace(/^@+/, "");
    if (Object.keys(patch).length === 0) {
      throw new ToolError("Provide at least one field to update.");
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").update(patch).eq("id", ctx.getUserId() ?? "").select(
      "id, social_media_handle, subscribe_order_updates, subscribe_promotions, subscribe_sms_promotions, updated_at"
    ).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No registration profile found for this account." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { registration: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qsunfiextzzdxnsyrkkc";
var mcp_default = defineMcp({
  name: "bright-start-flow",
  title: "Bright Start Flow",
  version: "0.1.0",
  instructions: "Tools for the Drop Dead Extensions pro registration app. Every tool acts as the signed-in user: read their wholesale registration profile, review their marketing consent history, and update their communication preferences or Instagram handle.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_registration_default, list_my_marketing_consent_default, update_my_communication_preferences_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
